# Generated by Django 5.2.6 on 2025-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steprecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='steprecord',
            name='steps',
            field=models.PositiveIntegerField(),
        ),
    ]
