# Generated by Django 5.2.6 on 2025-09-17 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_alter_steprecord_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steprecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='steprecord',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='steprecord',
            unique_together={('user', 'date')},

        ),
    ]
